/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * API Documentation
 * API documentation for the Click Proposta v1.0.0
 * OpenAPI spec version: 1.0.0
 */
import { apiMutator } from '../lib/axios';
export type CreateNewCustomerBody = {
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /**
   * @minLength 10
   * @maxLength 12
   * @pattern ^\d+$
   */
  phone: string;
};

export type CreateNewCustomer201 = {
  message: string;
  statusCode: number;
};

export type CreateNewCustomer400 = {
  message: string;
  statusCode: number;
};

export type FetchCustomers200CustomersItem = {
  name: string;
  id: string;
  email: string;
  phone: string;
};

export type FetchCustomers200 = {
  customers: FetchCustomers200CustomersItem[];
  statusCode: number;
};

export type FetchCustomers404 = {
  message: string;
  statusCode: number;
};

export type SearchByNameEmailParams = {
search: string;
};

export type SearchByNameEmail200CustomersItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /**
   * @minLength 10
   * @maxLength 15
   */
  phone: string;
  createdAt: string;
  updatedAt: string;
};

export type SearchByNameEmail200 = {
  customers: SearchByNameEmail200CustomersItem[];
};

export type SearchByNameEmail404 = {
  message: string;
};

export type SearchByNameEmail500 = {
  message: string;
};

export type CompleteRegisterBody = {
  /**
   * @minLength 10
   * @maxLength 11
   */
  phone: string;
  /**
   * @minLength 11
   * @maxLength 11
   */
  cpf: string;
};

export type CompleteRegister406 = {
  message: string;
};

export type CompleteRegister500 = {
  message: string;
};

export type GetCompleteRegister200 = {
  isRegisterComplete?: boolean;
};

export type GetCompleteRegister404 = {
  message: string;
};

export type GetCompleteRegister500 = {
  message: string;
  error?: string;
};

export type GetDataForPayment200 = {
  name: string;
  email: string;
  phone: string;
  cpf: string;
};

export type GetDataForPayment404 = {
  message: string;
};

export type GetDataForPayment422 = {
  message: string;
};

export type GetDataForPayment500 = {
  message: string;
};

export type GetMe200UserName = string |  | null;

export type GetMe200UserAvatarUrl = string |  | null;

export type GetMe200UserPlan = typeof GetMe200UserPlan[keyof typeof GetMe200UserPlan];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMe200UserPlan = {
  FREE: 'FREE',
  PRO: 'PRO',
} as const;

export type GetMe200User = {
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: GetMe200UserName;
  avatarUrl: GetMe200UserAvatarUrl;
  plan: GetMe200UserPlan;
  isRegisterComplete: boolean;
};

export type GetMe200 = {
  user: GetMe200User;
};

export type GetMe404 = {
  message: string;
};

export type GetMe500 = {
  message: string;
};

export type CreateServiceBody = {
  name: string;
  description?: string;
};

export type CreateService201 = {
  message: string;
  statusCode: number;
};

export type CreateService500 = {
  message: string;
  statusCode: number;
};

export type FetchManyServices200ServicesItemDescription = string |  | null;

export type FetchManyServices200ServicesItem = {
  id: string;
  name: string;
  description: FetchManyServices200ServicesItemDescription;
};

export type FetchManyServices200 = {
  services: FetchManyServices200ServicesItem[];
  statusCode: number;
};

export type FetchManyServices500 = {
  message: string;
  statusCode: number;
};

export type DeleteService200 = {
  statusCode: number;
};

export type DeleteService500 = {
  message: string;
  statusCode: number;
};

export type UpdateServiceBody = {
  name?: string;
  description?: string;
};

export type UpdateService200 = {
  statusCode: number;
};

export type UpdateService500 = {
  message: string;
  statusCode: number;
};

export type CreateProposalBodyUrlLogoImage = string |  | null;

export type CreateProposalBodyServicesItem = {
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  price: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  servicesId: string;
};

export type CreateProposalBody = {
  urlLogoImage: CreateProposalBodyUrlLogoImage;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  customersId: string;
  /** @minLength 1 */
  welcomeDescription: string;
  /** @minLength 1 */
  whyUs: string;
  /** @minLength 1 */
  challenge: string;
  /** @minLength 1 */
  solution: string;
  /** @minItems 1 */
  services: CreateProposalBodyServicesItem[];
  /** @minLength 1 */
  results: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  discount: number;
};

export type FetchMinimalDetailsProposal200ItemStatus = typeof FetchMinimalDetailsProposal200ItemStatus[keyof typeof FetchMinimalDetailsProposal200ItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FetchMinimalDetailsProposal200ItemStatus = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export type FetchMinimalDetailsProposal200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /**
   * @minLength 2
   * @maxLength 100
   */
  title: string;
  totalPrice: string;
  status: FetchMinimalDetailsProposal200ItemStatus;
};

export type FetchMinimalDetailsProposal500 = {
  message: string;
};

export type GetProposalById200UrlLogoImage = string |  | null;

export type GetProposalById200WelcomeDescription = string |  | null;

export type GetProposalById200WhyUs = string |  | null;

export type GetProposalById200Challenge = string |  | null;

export type GetProposalById200Solution = string |  | null;

export type GetProposalById200Results = string |  | null;

export type GetProposalById200Discount = number |  | null;

export type GetProposalById200TotalPrice = string |  | null;

export type GetProposalById200ServicesItem = {
  price: string;
  name: string;
};

export type GetProposalById200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  urlLogoImage: GetProposalById200UrlLogoImage;
  customersId: string;
  welcomeDescription: GetProposalById200WelcomeDescription;
  whyUs: GetProposalById200WhyUs;
  challenge: GetProposalById200Challenge;
  solution: GetProposalById200Solution;
  results: GetProposalById200Results;
  discount: GetProposalById200Discount;
  totalPrice: GetProposalById200TotalPrice;
  userId: string;
  customerName: string;
  services: GetProposalById200ServicesItem[];
};

export type GetProposalById500 = {
  error: string;
};

export type UpdateProposalBodyWelcomeDescription = string |  | null;

export type UpdateProposalBodyWhyUs = string |  | null;

export type UpdateProposalBodyChallenge = string |  | null;

export type UpdateProposalBodySolution = string |  | null;

export type UpdateProposalBodyResults = string |  | null;

export type UpdateProposalBody = {
  title?: string;
  welcomeDescription?: UpdateProposalBodyWelcomeDescription;
  whyUs?: UpdateProposalBodyWhyUs;
  challenge?: UpdateProposalBodyChallenge;
  solution?: UpdateProposalBodySolution;
  results?: UpdateProposalBodyResults;
  discount?: number;
  totalPrice?: number;
};

export type UpdateProposal400 = {
  message: string;
};

export type UpdateProposal500 = {
  message: string;
};

export type ConfirmSendingProposal204 = {
  statusCode: number;
};

export type ConfirmSendingProposal500 = {
  error: string;
};

export type ApproveProposal204 = {
  statusCode: number;
};

export type ApproveProposal500 = {
  error: string;
};

export type RecuseProposal204 = {
  message: string;
};

export type RecuseProposal404 = {
  message: string;
};

export type RecuseProposal500 = {
  message: string;
};

export type GetCustomerById200Customer = {
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /**
   * @minLength 10
   * @maxLength 15
   */
  phone: string;
  createdAt: string;
  updatedAt: string;
};

export type GetCustomerById200 = {
  customer: GetCustomerById200Customer;
};

export type GetCustomerById404 = {
  message: string;
};

export type CreateNewPaymentBodyCustomer = {
  /** @minLength 3 */
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /**
   * @minLength 10
   * @maxLength 11
   */
  cellphone: string;
  /**
   * @minLength 11
   * @maxLength 14
   */
  cpf: string;
};

export type CreateNewPaymentBody = {
  price?: number;
  quantity?: number;
  customer: CreateNewPaymentBodyCustomer;
};

export type CreateNewPayment500 = {
  message: string;
};

export type ConfirmPaymentParams = {
webhookSecret: string;
};

export type ConfirmPaymentBodyDataBillingCustomerMetadata = {
  cellphone: string;
  email: string;
  name: string;
  taxId: string;
};

export type ConfirmPaymentBodyDataBillingCustomer = {
  id: string;
  metadata: ConfirmPaymentBodyDataBillingCustomerMetadata;
};

export type ConfirmPaymentBodyDataBillingProductsItem = {
  externalId: string;
  id: string;
  quantity: number;
};

export type ConfirmPaymentBodyDataBilling = {
  amount: number;
  couponsUsed: unknown[];
  customer: ConfirmPaymentBodyDataBillingCustomer;
  frequency: string;
  id: string;
  kind: string[];
  paidAmount: number;
  products: ConfirmPaymentBodyDataBillingProductsItem[];
  status: string;
};

export type ConfirmPaymentBodyDataPayment = {
  amount: number;
  fee: number;
  method: string;
};

export type ConfirmPaymentBodyData = {
  billing: ConfirmPaymentBodyDataBilling;
  payment: ConfirmPaymentBodyDataPayment;
};

export type ConfirmPaymentBody = {
  data: ConfirmPaymentBodyData;
  devMode: boolean;
  event: string;
};

export type CreateProposalDraftBody = {
  /**
   * @minLength 10
   * @maxLength 5000
   */
  userPrompt: string;
};

export type CreateProposalDraft404 = {
  message: string;
};

export type CreateProposalDraft500 = {
  message: string;
};

export type GetLastDraftProposal200ProposalDraft = {
  title: string;
  welcomeDescription: string;
  whyUs: string;
  challenge: string;
  solution: string;
  results: string;
};

export type GetLastDraftProposal200 = {
  proposalDraft: GetLastDraftProposal200ProposalDraft;
};

export type GetLastDraftProposal404 = {
  message: string;
};

export type GetLastDraftProposal500 = {
  message: string;
};

export type PostPdfGenerateBodyServicesItem = {
  id: string;
  name: string;
  description: string;
};

export type PostPdfGenerateBody = {
  imgUrl: string;
  nameUser: string;
  nameCustomer: string;
  emailCustomer: string;
  phoneCustomer: string;
  total: string;
  services: PostPdfGenerateBodyServicesItem[];
};

export type PostBudgetsBodyServicesItem = {
  id: string;
  name: string;
  description: string;
};

export type PostBudgetsBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  customerId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  total: number;
  services: PostBudgetsBodyServicesItem[];
};

export type PostBudgets404 = {
  message: string;
};

export type GetByIdBudget200BudgetBudgetsServicesItem = {
  id: string;
  title: string;
  description: string;
};

export type GetByIdBudget200Budget = {
  id: string;
  total: number;
  status: string;
  customersId: string;
  budgetsServices: GetByIdBudget200BudgetBudgetsServicesItem[];
};

export type GetByIdBudget200 = {
  budget: GetByIdBudget200Budget;
};

export type GetByIdBudget404 = {
  message: string;
};

export const createNewCustomer = (
    createNewCustomerBody: CreateNewCustomerBody,
 ) => {
      return apiMutator<CreateNewCustomer201>(
      {url: `/user/customer/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNewCustomerBody
    },
      );
    }
  
export const fetchCustomers = (
    
 ) => {
      return apiMutator<FetchCustomers200>(
      {url: `/user/customers`, method: 'GET'
    },
      );
    }
  
export const searchByNameEmail = (
    params: SearchByNameEmailParams,
 ) => {
      return apiMutator<SearchByNameEmail200>(
      {url: `/search-by-name-email`, method: 'GET',
        params
    },
      );
    }
  
export const completeRegister = (
    completeRegisterBody: CompleteRegisterBody,
 ) => {
      return apiMutator<unknown>(
      {url: `/complete-register`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: completeRegisterBody
    },
      );
    }
  
export const getCompleteRegister = (
    
 ) => {
      return apiMutator<GetCompleteRegister200>(
      {url: `/is-complete-register`, method: 'GET'
    },
      );
    }
  
export const getDataForPayment = (
    
 ) => {
      return apiMutator<GetDataForPayment200>(
      {url: `/data-for-payment`, method: 'GET'
    },
      );
    }
  
export const getMe = (
    
 ) => {
      return apiMutator<GetMe200>(
      {url: `/me`, method: 'GET'
    },
      );
    }
  
export const createService = (
    createServiceBody: CreateServiceBody,
 ) => {
      return apiMutator<CreateService201>(
      {url: `/service`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createServiceBody
    },
      );
    }
  
export const fetchManyServices = (
    
 ) => {
      return apiMutator<FetchManyServices200>(
      {url: `/services`, method: 'GET'
    },
      );
    }
  
export const deleteService = (
    idService: string,
 ) => {
      return apiMutator<DeleteService200>(
      {url: `/services/${idService}`, method: 'DELETE'
    },
      );
    }
  
export const updateService = (
    idService: string,
    updateServiceBody: UpdateServiceBody,
 ) => {
      return apiMutator<UpdateService200>(
      {url: `/services/${idService}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateServiceBody
    },
      );
    }
  
export const createProposal = (
    createProposalBody: CreateProposalBody,
 ) => {
      return apiMutator<void>(
      {url: `/proposal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProposalBody
    },
      );
    }
  
export const fetchMinimalDetailsProposal = (
    
 ) => {
      return apiMutator<FetchMinimalDetailsProposal200Item[]>(
      {url: `/proposals/minimal-details`, method: 'GET'
    },
      );
    }
  
export const getProposalById = (
    id: string,
 ) => {
      return apiMutator<GetProposalById200>(
      {url: `/proposal/${id}`, method: 'GET'
    },
      );
    }
  
export const updateProposal = (
    proposalId: string,
    updateProposalBody: UpdateProposalBody,
 ) => {
      return apiMutator<unknown>(
      {url: `/proposal/${proposalId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProposalBody
    },
      );
    }
  
export const confirmSendingProposal = (
    proposalId: string,
 ) => {
      return apiMutator<ConfirmSendingProposal204>(
      {url: `/proposal/confirm-sending/${proposalId}`, method: 'PATCH'
    },
      );
    }
  
export const approveProposal = (
    proposalId: string,
 ) => {
      return apiMutator<ApproveProposal204>(
      {url: `/proposal/approve-proposal/${proposalId}`, method: 'PATCH'
    },
      );
    }
  
export const recuseProposal = (
    id: string,
 ) => {
      return apiMutator<RecuseProposal204>(
      {url: `/proposals/${id}/recuse`, method: 'PATCH'
    },
      );
    }
  
export const getCustomerById = (
    customerId: string,
 ) => {
      return apiMutator<GetCustomerById200>(
      {url: `/customer/${customerId}`, method: 'GET'
    },
      );
    }
  
export const createNewPayment = (
    createNewPaymentBody: CreateNewPaymentBody,
 ) => {
      return apiMutator<string>(
      {url: `/payment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNewPaymentBody
    },
      );
    }
  
export const confirmPayment = (
    confirmPaymentBody: ConfirmPaymentBody,
    params: ConfirmPaymentParams,
 ) => {
      return apiMutator<void>(
      {url: `/confirm-payment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: confirmPaymentBody,
        params
    },
      );
    }
  
export const createProposalDraft = (
    customerId: string,
    createProposalDraftBody: CreateProposalDraftBody,
 ) => {
      return apiMutator<unknown>(
      {url: `/draft-proposals/${customerId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProposalDraftBody
    },
      );
    }
  
export const getLastDraftProposal = (
    customerId: string,
 ) => {
      return apiMutator<GetLastDraftProposal200>(
      {url: `/draft-proposals/${customerId}/last`, method: 'GET'
    },
      );
    }
  
export const postPdfGenerate = (
    postPdfGenerateBody: PostPdfGenerateBody,
 ) => {
      return apiMutator<void>(
      {url: `/pdf/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postPdfGenerateBody
    },
      );
    }
  
export const postBudgets = (
    postBudgetsBody: PostBudgetsBody,
 ) => {
      return apiMutator<unknown>(
      {url: `/budgets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postBudgetsBody
    },
      );
    }
  
export const getByIdBudget = (
    budgetId: string,
 ) => {
      return apiMutator<GetByIdBudget200>(
      {url: `/budgets/${budgetId}`, method: 'GET'
    },
      );
    }
  
export type CreateNewCustomerResult = NonNullable<Awaited<ReturnType<typeof createNewCustomer>>>
export type FetchCustomersResult = NonNullable<Awaited<ReturnType<typeof fetchCustomers>>>
export type SearchByNameEmailResult = NonNullable<Awaited<ReturnType<typeof searchByNameEmail>>>
export type CompleteRegisterResult = NonNullable<Awaited<ReturnType<typeof completeRegister>>>
export type GetCompleteRegisterResult = NonNullable<Awaited<ReturnType<typeof getCompleteRegister>>>
export type GetDataForPaymentResult = NonNullable<Awaited<ReturnType<typeof getDataForPayment>>>
export type GetMeResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type CreateServiceResult = NonNullable<Awaited<ReturnType<typeof createService>>>
export type FetchManyServicesResult = NonNullable<Awaited<ReturnType<typeof fetchManyServices>>>
export type DeleteServiceResult = NonNullable<Awaited<ReturnType<typeof deleteService>>>
export type UpdateServiceResult = NonNullable<Awaited<ReturnType<typeof updateService>>>
export type CreateProposalResult = NonNullable<Awaited<ReturnType<typeof createProposal>>>
export type FetchMinimalDetailsProposalResult = NonNullable<Awaited<ReturnType<typeof fetchMinimalDetailsProposal>>>
export type GetProposalByIdResult = NonNullable<Awaited<ReturnType<typeof getProposalById>>>
export type UpdateProposalResult = NonNullable<Awaited<ReturnType<typeof updateProposal>>>
export type ConfirmSendingProposalResult = NonNullable<Awaited<ReturnType<typeof confirmSendingProposal>>>
export type ApproveProposalResult = NonNullable<Awaited<ReturnType<typeof approveProposal>>>
export type RecuseProposalResult = NonNullable<Awaited<ReturnType<typeof recuseProposal>>>
export type GetCustomerByIdResult = NonNullable<Awaited<ReturnType<typeof getCustomerById>>>
export type CreateNewPaymentResult = NonNullable<Awaited<ReturnType<typeof createNewPayment>>>
export type ConfirmPaymentResult = NonNullable<Awaited<ReturnType<typeof confirmPayment>>>
export type CreateProposalDraftResult = NonNullable<Awaited<ReturnType<typeof createProposalDraft>>>
export type GetLastDraftProposalResult = NonNullable<Awaited<ReturnType<typeof getLastDraftProposal>>>
export type PostPdfGenerateResult = NonNullable<Awaited<ReturnType<typeof postPdfGenerate>>>
export type PostBudgetsResult = NonNullable<Awaited<ReturnType<typeof postBudgets>>>
export type GetByIdBudgetResult = NonNullable<Awaited<ReturnType<typeof getByIdBudget>>>
