/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as LoginRouteImport } from './pages/login'
import { Route as AuthenticatedRouteImport } from './pages/_authenticated'
import { Route as IndexRouteImport } from './pages/index'
import { Route as PublicProposalProposalIdRouteImport } from './pages/public-proposal/$proposal-id'
import { Route as PublicBudgetBudgetIdRouteImport } from './pages/public-budget/$budget-id'
import { Route as AuthCallbackRouteImport } from './pages/auth/callback'
import { Route as AuthenticatedSuccessPaymentRouteImport } from './pages/_authenticated/success-payment'
import { Route as AuthenticatedProposalsRouteImport } from './pages/_authenticated/proposals'
import { Route as AuthenticatedPlansRouteImport } from './pages/_authenticated/plans'
import { Route as AuthenticatedMyServicesRouteImport } from './pages/_authenticated/my-services'
import { Route as AuthenticatedDashboardRouteImport } from './pages/_authenticated/dashboard'
import { Route as AuthenticatedBudgetsRouteImport } from './pages/_authenticated/budgets'
import { Route as AuthenticatedProposalProposalIdRouteImport } from './pages/_authenticated/proposal/$proposal-id'
import { Route as AuthenticatedClickAiCustomerIdRouteImport } from './pages/_authenticated/click-ai/$customer-id'
import { Route as AuthenticatedBudgetBudgetIdRouteImport } from './pages/_authenticated/budget/$budget-id'
import { Route as AuthenticatedBudgetProductsCustomerIdRouteImport } from './pages/_authenticated/budget-products/$customer-id'
import { Route as AuthenticatedBudgetCivilCustomerIdRouteImport } from './pages/_authenticated/budget-civil/$customer-id'
import { Route as AuthenticatedCreateProposalSelectTypeProposalRouteImport } from './pages/_authenticated/_create-proposal/select-type-proposal'
import { Route as AuthenticatedCreateProposalSelectCostumerRouteImport } from './pages/_authenticated/_create-proposal/select-costumer'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProposalProposalIdRoute =
  PublicProposalProposalIdRouteImport.update({
    id: '/public-proposal/$proposal-id',
    path: '/public-proposal/$proposal-id',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicBudgetBudgetIdRoute = PublicBudgetBudgetIdRouteImport.update({
  id: '/public-budget/$budget-id',
  path: '/public-budget/$budget-id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuccessPaymentRoute =
  AuthenticatedSuccessPaymentRouteImport.update({
    id: '/success-payment',
    path: '/success-payment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProposalsRoute = AuthenticatedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyServicesRoute = AuthenticatedMyServicesRouteImport.update({
  id: '/my-services',
  path: '/my-services',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProposalProposalIdRoute =
  AuthenticatedProposalProposalIdRouteImport.update({
    id: '/proposal/$proposal-id',
    path: '/proposal/$proposal-id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClickAiCustomerIdRoute =
  AuthenticatedClickAiCustomerIdRouteImport.update({
    id: '/click-ai/$customer-id',
    path: '/click-ai/$customer-id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetBudgetIdRoute =
  AuthenticatedBudgetBudgetIdRouteImport.update({
    id: '/budget/$budget-id',
    path: '/budget/$budget-id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetProductsCustomerIdRoute =
  AuthenticatedBudgetProductsCustomerIdRouteImport.update({
    id: '/budget-products/$customer-id',
    path: '/budget-products/$customer-id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetCivilCustomerIdRoute =
  AuthenticatedBudgetCivilCustomerIdRouteImport.update({
    id: '/budget-civil/$customer-id',
    path: '/budget-civil/$customer-id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreateProposalSelectTypeProposalRoute =
  AuthenticatedCreateProposalSelectTypeProposalRouteImport.update({
    id: '/_create-proposal/select-type-proposal',
    path: '/select-type-proposal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreateProposalSelectCostumerRoute =
  AuthenticatedCreateProposalSelectCostumerRouteImport.update({
    id: '/_create-proposal/select-costumer',
    path: '/select-costumer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-services': typeof AuthenticatedMyServicesRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/success-payment': typeof AuthenticatedSuccessPaymentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/public-budget/$budget-id': typeof PublicBudgetBudgetIdRoute
  '/public-proposal/$proposal-id': typeof PublicProposalProposalIdRoute
  '/select-costumer': typeof AuthenticatedCreateProposalSelectCostumerRoute
  '/select-type-proposal': typeof AuthenticatedCreateProposalSelectTypeProposalRoute
  '/budget-civil/$customer-id': typeof AuthenticatedBudgetCivilCustomerIdRoute
  '/budget-products/$customer-id': typeof AuthenticatedBudgetProductsCustomerIdRoute
  '/budget/$budget-id': typeof AuthenticatedBudgetBudgetIdRoute
  '/click-ai/$customer-id': typeof AuthenticatedClickAiCustomerIdRoute
  '/proposal/$proposal-id': typeof AuthenticatedProposalProposalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-services': typeof AuthenticatedMyServicesRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/success-payment': typeof AuthenticatedSuccessPaymentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/public-budget/$budget-id': typeof PublicBudgetBudgetIdRoute
  '/public-proposal/$proposal-id': typeof PublicProposalProposalIdRoute
  '/select-costumer': typeof AuthenticatedCreateProposalSelectCostumerRoute
  '/select-type-proposal': typeof AuthenticatedCreateProposalSelectTypeProposalRoute
  '/budget-civil/$customer-id': typeof AuthenticatedBudgetCivilCustomerIdRoute
  '/budget-products/$customer-id': typeof AuthenticatedBudgetProductsCustomerIdRoute
  '/budget/$budget-id': typeof AuthenticatedBudgetBudgetIdRoute
  '/click-ai/$customer-id': typeof AuthenticatedClickAiCustomerIdRoute
  '/proposal/$proposal-id': typeof AuthenticatedProposalProposalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-services': typeof AuthenticatedMyServicesRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/proposals': typeof AuthenticatedProposalsRoute
  '/_authenticated/success-payment': typeof AuthenticatedSuccessPaymentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/public-budget/$budget-id': typeof PublicBudgetBudgetIdRoute
  '/public-proposal/$proposal-id': typeof PublicProposalProposalIdRoute
  '/_authenticated/_create-proposal/select-costumer': typeof AuthenticatedCreateProposalSelectCostumerRoute
  '/_authenticated/_create-proposal/select-type-proposal': typeof AuthenticatedCreateProposalSelectTypeProposalRoute
  '/_authenticated/budget-civil/$customer-id': typeof AuthenticatedBudgetCivilCustomerIdRoute
  '/_authenticated/budget-products/$customer-id': typeof AuthenticatedBudgetProductsCustomerIdRoute
  '/_authenticated/budget/$budget-id': typeof AuthenticatedBudgetBudgetIdRoute
  '/_authenticated/click-ai/$customer-id': typeof AuthenticatedClickAiCustomerIdRoute
  '/_authenticated/proposal/$proposal-id': typeof AuthenticatedProposalProposalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/budgets'
    | '/dashboard'
    | '/my-services'
    | '/plans'
    | '/proposals'
    | '/success-payment'
    | '/auth/callback'
    | '/public-budget/$budget-id'
    | '/public-proposal/$proposal-id'
    | '/select-costumer'
    | '/select-type-proposal'
    | '/budget-civil/$customer-id'
    | '/budget-products/$customer-id'
    | '/budget/$budget-id'
    | '/click-ai/$customer-id'
    | '/proposal/$proposal-id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/budgets'
    | '/dashboard'
    | '/my-services'
    | '/plans'
    | '/proposals'
    | '/success-payment'
    | '/auth/callback'
    | '/public-budget/$budget-id'
    | '/public-proposal/$proposal-id'
    | '/select-costumer'
    | '/select-type-proposal'
    | '/budget-civil/$customer-id'
    | '/budget-products/$customer-id'
    | '/budget/$budget-id'
    | '/click-ai/$customer-id'
    | '/proposal/$proposal-id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/budgets'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-services'
    | '/_authenticated/plans'
    | '/_authenticated/proposals'
    | '/_authenticated/success-payment'
    | '/auth/callback'
    | '/public-budget/$budget-id'
    | '/public-proposal/$proposal-id'
    | '/_authenticated/_create-proposal/select-costumer'
    | '/_authenticated/_create-proposal/select-type-proposal'
    | '/_authenticated/budget-civil/$customer-id'
    | '/_authenticated/budget-products/$customer-id'
    | '/_authenticated/budget/$budget-id'
    | '/_authenticated/click-ai/$customer-id'
    | '/_authenticated/proposal/$proposal-id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PublicBudgetBudgetIdRoute: typeof PublicBudgetBudgetIdRoute
  PublicProposalProposalIdRoute: typeof PublicProposalProposalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-proposal/$proposal-id': {
      id: '/public-proposal/$proposal-id'
      path: '/public-proposal/$proposal-id'
      fullPath: '/public-proposal/$proposal-id'
      preLoaderRoute: typeof PublicProposalProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-budget/$budget-id': {
      id: '/public-budget/$budget-id'
      path: '/public-budget/$budget-id'
      fullPath: '/public-budget/$budget-id'
      preLoaderRoute: typeof PublicBudgetBudgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/success-payment': {
      id: '/_authenticated/success-payment'
      path: '/success-payment'
      fullPath: '/success-payment'
      preLoaderRoute: typeof AuthenticatedSuccessPaymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proposals': {
      id: '/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedProposalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-services': {
      id: '/_authenticated/my-services'
      path: '/my-services'
      fullPath: '/my-services'
      preLoaderRoute: typeof AuthenticatedMyServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proposal/$proposal-id': {
      id: '/_authenticated/proposal/$proposal-id'
      path: '/proposal/$proposal-id'
      fullPath: '/proposal/$proposal-id'
      preLoaderRoute: typeof AuthenticatedProposalProposalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/click-ai/$customer-id': {
      id: '/_authenticated/click-ai/$customer-id'
      path: '/click-ai/$customer-id'
      fullPath: '/click-ai/$customer-id'
      preLoaderRoute: typeof AuthenticatedClickAiCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget/$budget-id': {
      id: '/_authenticated/budget/$budget-id'
      path: '/budget/$budget-id'
      fullPath: '/budget/$budget-id'
      preLoaderRoute: typeof AuthenticatedBudgetBudgetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget-products/$customer-id': {
      id: '/_authenticated/budget-products/$customer-id'
      path: '/budget-products/$customer-id'
      fullPath: '/budget-products/$customer-id'
      preLoaderRoute: typeof AuthenticatedBudgetProductsCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget-civil/$customer-id': {
      id: '/_authenticated/budget-civil/$customer-id'
      path: '/budget-civil/$customer-id'
      fullPath: '/budget-civil/$customer-id'
      preLoaderRoute: typeof AuthenticatedBudgetCivilCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_create-proposal/select-type-proposal': {
      id: '/_authenticated/_create-proposal/select-type-proposal'
      path: '/select-type-proposal'
      fullPath: '/select-type-proposal'
      preLoaderRoute: typeof AuthenticatedCreateProposalSelectTypeProposalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_create-proposal/select-costumer': {
      id: '/_authenticated/_create-proposal/select-costumer'
      path: '/select-costumer'
      fullPath: '/select-costumer'
      preLoaderRoute: typeof AuthenticatedCreateProposalSelectCostumerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyServicesRoute: typeof AuthenticatedMyServicesRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProposalsRoute: typeof AuthenticatedProposalsRoute
  AuthenticatedSuccessPaymentRoute: typeof AuthenticatedSuccessPaymentRoute
  AuthenticatedCreateProposalSelectCostumerRoute: typeof AuthenticatedCreateProposalSelectCostumerRoute
  AuthenticatedCreateProposalSelectTypeProposalRoute: typeof AuthenticatedCreateProposalSelectTypeProposalRoute
  AuthenticatedBudgetCivilCustomerIdRoute: typeof AuthenticatedBudgetCivilCustomerIdRoute
  AuthenticatedBudgetProductsCustomerIdRoute: typeof AuthenticatedBudgetProductsCustomerIdRoute
  AuthenticatedBudgetBudgetIdRoute: typeof AuthenticatedBudgetBudgetIdRoute
  AuthenticatedClickAiCustomerIdRoute: typeof AuthenticatedClickAiCustomerIdRoute
  AuthenticatedProposalProposalIdRoute: typeof AuthenticatedProposalProposalIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyServicesRoute: AuthenticatedMyServicesRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProposalsRoute: AuthenticatedProposalsRoute,
  AuthenticatedSuccessPaymentRoute: AuthenticatedSuccessPaymentRoute,
  AuthenticatedCreateProposalSelectCostumerRoute:
    AuthenticatedCreateProposalSelectCostumerRoute,
  AuthenticatedCreateProposalSelectTypeProposalRoute:
    AuthenticatedCreateProposalSelectTypeProposalRoute,
  AuthenticatedBudgetCivilCustomerIdRoute:
    AuthenticatedBudgetCivilCustomerIdRoute,
  AuthenticatedBudgetProductsCustomerIdRoute:
    AuthenticatedBudgetProductsCustomerIdRoute,
  AuthenticatedBudgetBudgetIdRoute: AuthenticatedBudgetBudgetIdRoute,
  AuthenticatedClickAiCustomerIdRoute: AuthenticatedClickAiCustomerIdRoute,
  AuthenticatedProposalProposalIdRoute: AuthenticatedProposalProposalIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PublicBudgetBudgetIdRoute: PublicBudgetBudgetIdRoute,
  PublicProposalProposalIdRoute: PublicProposalProposalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
